source:
  uri: oakland/in/street_lights_geo.jsonlines
  format: jsonlines

transform:
  tasks:
    - type: project
      schema:
        properties.id: $.properties.OBJECTID
        properties.street_number: $.properties.STNO
        properties.street_name: $.properties.STREET_NAM
        geometry: $.geometry

sink:
  uri: oakland/out/street_lights.jsonlines
  format: jsonlines
